#!/usr/bin/env php
<?php

declare(strict_types=1);

require_once __DIR__ . "/vendor/autoload.php";
require_once __DIR__ . "/bootstrap/app.php";

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

$app = \createApp();

$kernel = $app->make(
    "Illuminate\Contracts\Console\Kernel"
);

exit($kernel->handle(new ArgvInput, new ConsoleOutput));
